version: "3.2"
services: 
  node1:
    build: ../
    image:  batch_elixir:elixir
    environment: 
      KEY_REST_API: $KEY_REST_API
      KEY_API: $KEY_API
  node2:
    build: ../
    image:  batch_elixir:elixir
    environment: 
      KEY_REST_API: $KEY_REST_API
      KEY_API: $KEY_API
  test:
    build: ./
    image:  batch_elixir:nodejs
    ports: 
      - 3000:3000
    depends_on: 
      - nginx
  nginx:
    image: nginx:alpine
    depends_on: 
      - node1
      - node2
    ports: 
      - 8080:8080
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']